# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Wyzwania' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wyzwania
 pod 'Google-Mobile-Ads-SDK'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'OneSignal'
  pod 'ChartboostSDK'
  pod 'Firebase/Database'

end

target 'Wyzwania - desktop' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Wyzwania - desktop

end
